version: "3.9"

services:
  one4all:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: one4all
    environment:
      - DISPLAY=:0.0
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=6
    network_mode: host
    privileged: true
    volumes:
      - ./src/:/home/ros2_ws/src/
    command: bash -c "ros2 launch neo_simulation2 simulation.launch.py"