# Default initial positions for awcombo's ros2_control fake system

initial_positions:
  awtube_joint1: 0
  awtube_joint2: 0
  awtube_joint3: 0
  awtube_joint4: 0
  awtube_joint5: 0
  awtube_joint6: 0