# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  awtube_joint1:
    has_velocity_limits: true
    max_velocity: 1.2436
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0
  awtube_joint2:
    has_velocity_limits: true
    max_velocity: 0.85999999999999999
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0
  awtube_joint3:
    has_velocity_limits: true
    max_velocity: 1.24
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0
  awtube_joint4:
    has_velocity_limits: true
    max_velocity: 2.71
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0
  awtube_joint5:
    has_velocity_limits: true
    max_velocity: 2.71
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0
  awtube_joint6:
    has_velocity_limits: true
    max_velocity: 3.6099999999999999
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: false
    max_decelaration: 5.0

    # Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
