# MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
controller_names:
  - CSP

CSP:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  # default: true
  joints:
    - awtube_joint1
    - awtube_joint2
    - awtube_joint3
    - awtube_joint4
    - awtube_joint5
    - awtube_joint6
