# MoveIt uses this configuration for controller management

# moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
controller_names:
  - CSP

CSP:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  # default: true
  joints:
    - awtube2_18kg_v2_joint1
    - awtube2_18kg_v2_joint2
    - awtube2_18kg_v2_joint3
    - awtube2_18kg_v2_joint4
    - awtube2_18kg_v2_joint5
    - awtube2_18kg_v2_joint6
