# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    CSP:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

CSP:
  ros__parameters:
    joints:
      - awtube_joint1
      - awtube_joint2
      - awtube_joint3
      - awtube_joint4
      - awtube_joint5
      - awtube_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity